"""add_tenant_isolation

Revision ID: 9390e65e9384
Revises: ce04072dc963
Create Date: 2026-03-28 13:54:03.127100

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9390e65e9384'
down_revision: Union[str, None] = 'ce04072dc963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_owner_id'), 'alerts', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('behavior_logs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_behavior_logs_owner_id'), 'behavior_logs', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'behavior_logs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('detections', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_detections_owner_id'), 'detections', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'detections', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_owner_id'), 'events', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('farrowing_records', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_farrowing_records_owner_id'), 'farrowing_records', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'farrowing_records', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('notification_log', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notification_log_owner_id'), 'notification_log', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'notification_log', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('notification_subscriptions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notification_subscriptions_owner_id'), 'notification_subscriptions', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'notification_subscriptions', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('pens', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pens_owner_id'), 'pens', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'pens', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('piglet_records', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_piglet_records_owner_id'), 'piglet_records', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'piglet_records', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('recording_clips', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recording_clips_owner_id'), 'recording_clips', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'recording_clips', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('recording_schedules', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recording_schedules_owner_id'), 'recording_schedules', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'recording_schedules', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('sows', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sows_owner_id'), 'sows', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'sows', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('storage_status', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_storage_status_owner_id'), 'storage_status', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'storage_status', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('task_templates', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_templates_owner_id'), 'task_templates', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'task_templates', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_rules', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workflow_rules_owner_id'), 'workflow_rules', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'workflow_rules', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_rules', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_rules_owner_id'), table_name='workflow_rules')
    op.drop_column('workflow_rules', 'owner_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_column('tasks', 'owner_id')
    op.drop_constraint(None, 'task_templates', type_='foreignkey')
    op.drop_index(op.f('ix_task_templates_owner_id'), table_name='task_templates')
    op.drop_column('task_templates', 'owner_id')
    op.drop_constraint(None, 'storage_status', type_='foreignkey')
    op.drop_index(op.f('ix_storage_status_owner_id'), table_name='storage_status')
    op.drop_column('storage_status', 'owner_id')
    op.drop_constraint(None, 'sows', type_='foreignkey')
    op.drop_index(op.f('ix_sows_owner_id'), table_name='sows')
    op.drop_column('sows', 'owner_id')
    op.drop_constraint(None, 'recording_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_recording_schedules_owner_id'), table_name='recording_schedules')
    op.drop_column('recording_schedules', 'owner_id')
    op.drop_constraint(None, 'recording_clips', type_='foreignkey')
    op.drop_index(op.f('ix_recording_clips_owner_id'), table_name='recording_clips')
    op.drop_column('recording_clips', 'owner_id')
    op.drop_constraint(None, 'piglet_records', type_='foreignkey')
    op.drop_index(op.f('ix_piglet_records_owner_id'), table_name='piglet_records')
    op.drop_column('piglet_records', 'owner_id')
    op.drop_constraint(None, 'pens', type_='foreignkey')
    op.drop_index(op.f('ix_pens_owner_id'), table_name='pens')
    op.drop_column('pens', 'owner_id')
    op.drop_constraint(None, 'notification_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_notification_subscriptions_owner_id'), table_name='notification_subscriptions')
    op.drop_column('notification_subscriptions', 'owner_id')
    op.drop_constraint(None, 'notification_log', type_='foreignkey')
    op.drop_index(op.f('ix_notification_log_owner_id'), table_name='notification_log')
    op.drop_column('notification_log', 'owner_id')
    op.drop_constraint(None, 'farrowing_records', type_='foreignkey')
    op.drop_index(op.f('ix_farrowing_records_owner_id'), table_name='farrowing_records')
    op.drop_column('farrowing_records', 'owner_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_owner_id'), table_name='events')
    op.drop_column('events', 'owner_id')
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_index(op.f('ix_detections_owner_id'), table_name='detections')
    op.drop_column('detections', 'owner_id')
    op.drop_constraint(None, 'behavior_logs', type_='foreignkey')
    op.drop_index(op.f('ix_behavior_logs_owner_id'), table_name='behavior_logs')
    op.drop_column('behavior_logs', 'owner_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_owner_id'), table_name='alerts')
    op.drop_column('alerts', 'owner_id')
    # ### end Alembic commands ###
