"""add_recording_tables

Revision ID: ce04072dc963
Revises: 8cbbf10f1a44
Create Date: 2026-03-27 23:57:25.055511

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce04072dc963'
down_revision: Union[str, None] = '8cbbf10f1a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pen_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('edge_device_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pen_id'], ['pens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pen_id', sa.Integer(), nullable=True),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pen_id'], ['pens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pen_id', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('free_bytes', sa.BigInteger(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pen_id'], ['pens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.alter_column('behavior_logs', 'archived_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('detections', 'sow_posture',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.alter_column('farrowing_records', 'pen_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('farrowing_records', 'farrowing_started',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('farrowing_records', 'farrowing_completed',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('farrowing_records', 'sow_condition',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'good'::character varying"))
    op.alter_column('farrowing_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('farrowing_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_farrowing_records_farrowing_started'), table_name='farrowing_records')
    op.drop_index(op.f('ix_farrowing_records_sow_id'), table_name='farrowing_records')
    op.create_index(op.f('ix_farrowing_records_id'), 'farrowing_records', ['id'], unique=False)
    op.create_index(op.f('ix_pens_id'), 'pens', ['id'], unique=False)
    op.alter_column('piglet_records', 'temp_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('piglet_records', 'birth_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('piglet_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True,
               existing_server_default=sa.text("'alive'::character varying"))
    op.alter_column('piglet_records', 'death_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('piglet_records', 'processed_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('piglet_records', 'health_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('piglet_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('piglet_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_piglet_records_ear_tag'), table_name='piglet_records')
    op.drop_index(op.f('ix_piglet_records_farrowing_record_id'), table_name='piglet_records')
    op.drop_index(op.f('ix_piglet_records_status'), table_name='piglet_records')
    op.create_index(op.f('ix_piglet_records_id'), 'piglet_records', ['id'], unique=False)
    op.create_unique_constraint(None, 'piglet_records', ['ear_tag'])
    op.alter_column('sows', 'archived_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_sows_id'), 'sows', ['id'], unique=False)
    op.alter_column('task_templates', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('task_templates', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('task_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_task_templates_category'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_trigger_type'), table_name='task_templates')
    op.create_index(op.f('ix_task_templates_id'), 'task_templates', ['id'], unique=False)
    op.drop_column('task_templates', 'updated_at')
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('tasks', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('workflow_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('workflow_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_workflow_rules_trigger_event'), table_name='workflow_rules')
    op.create_index(op.f('ix_workflow_rules_id'), 'workflow_rules', ['id'], unique=False)
    op.create_foreign_key(None, 'workflow_rules', 'task_templates', ['task_template_id'], ['id'])
    op.drop_column('workflow_rules', 'conditions')
    op.drop_column('workflow_rules', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_rules', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('workflow_rules', sa.Column('conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow_rules', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_rules_id'), table_name='workflow_rules')
    op.create_index(op.f('ix_workflow_rules_trigger_event'), 'workflow_rules', ['trigger_event'], unique=False)
    op.alter_column('workflow_rules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workflow_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'scheduled_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.add_column('task_templates', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_templates_id'), table_name='task_templates')
    op.create_index(op.f('ix_task_templates_trigger_type'), 'task_templates', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_task_templates_category'), 'task_templates', ['category'], unique=False)
    op.alter_column('task_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('task_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('task_templates', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task_templates', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_sows_id'), table_name='sows')
    op.alter_column('sows', 'archived_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'piglet_records', type_='unique')
    op.drop_index(op.f('ix_piglet_records_id'), table_name='piglet_records')
    op.create_index(op.f('ix_piglet_records_status'), 'piglet_records', ['status'], unique=False)
    op.create_index(op.f('ix_piglet_records_farrowing_record_id'), 'piglet_records', ['farrowing_record_id'], unique=False)
    op.create_index(op.f('ix_piglet_records_ear_tag'), 'piglet_records', ['ear_tag'], unique=False)
    op.alter_column('piglet_records', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('piglet_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('piglet_records', 'health_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('piglet_records', 'processed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('piglet_records', 'death_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('piglet_records', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'alive'::character varying"))
    op.alter_column('piglet_records', 'birth_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('piglet_records', 'temp_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_pens_id'), table_name='pens')
    op.drop_index(op.f('ix_farrowing_records_id'), table_name='farrowing_records')
    op.create_index(op.f('ix_farrowing_records_sow_id'), 'farrowing_records', ['sow_id'], unique=False)
    op.create_index(op.f('ix_farrowing_records_farrowing_started'), 'farrowing_records', ['farrowing_started'], unique=False)
    op.alter_column('farrowing_records', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('farrowing_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('farrowing_records', 'sow_condition',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'good'::character varying"))
    op.alter_column('farrowing_records', 'farrowing_completed',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('farrowing_records', 'farrowing_started',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('farrowing_records', 'pen_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.alter_column('detections', 'sow_posture',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('behavior_logs', 'archived_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('storage_status')
    op.drop_table('recording_schedules')
    op.drop_table('recording_clips')
    # ### end Alembic commands ###
